### ISSUE TITLE
Weekday calculation bug : Incorrect results when start day is a weekend.

### ISSUE THREAD

**Issue by BasilBibi** [ZakBibi/PracticePython#37]
Here is a test that shows the bug

    def test_05_weekend_start(self):
        start = '2018/11/03'
        end = '2018/11/13'
        self.assertEqual(5, weekdays_in_range(start, end))

**Comment by ZakBibi** [comment]
The test here is useful, but also the expected result is incorrect - there are 6 work days between these two dates. Running the test itself results in an actual result of 8, which is wrong. 

```python
def test_05_weekend_start(self):
    start = '2018/11/03'
    end = '2018/11/13'
    self.assertEqual(6, weekdays_in_range(start, end))
```
