### ISSUE TITLE
Create an abstract CustomerDao class and provide a concrete class CustomerJsonDao.

### ISSUE THREAD

**Issue by BasilBibi** [ZakBibi/PracticePython#53]
Build on the work you did with CustomerDetail.

Assume that customer_id is the primary key.

The interface for ```CustomerDao``` should be as follows : 

```
get_customers() : list
get_customer_by_id(cust_id) : CustomerDetail
get_customers_by_name(last_name, first_name) : list
get_customers_by_country(iso_country_code): list
```

#### Definition of Done
Write an Abstract ```CustomerDao``` class
Write a concrete ```CustomerJsonDao``` class with all abstract methods implemented.
Provide code supported by tests that prove all of the methods in the concrete class work.
Code adheres to clean code principles

**Comment by ZakBibi** [comment]
After discussion with the user, we agreed that get_customers_by_country(iso_country_code) is not a good method name, so we changed it in my build to get_customers_by_iso_country_code(iso_country_code) for readability and clarity.
