### ISSUE TITLE
Bug: has_common_tickers and tests failing. These were pushed onto develop without testing. 

### ISSUE THREAD

**Issue by ZakBibi** [ZakBibi/PracticePython#66]

**Comment by BasilBibi** [comment]
Good work, well done you fixed this very quickly.
What assumptions are your changes based on?

**Comment by ZakBibi** [comment]
My assumption was that the stock exchange lists would not be massive, therefore I decided to go with using the intersection found in common_tickers rather than a for loop. The for loop is more efficient, as it only has to find one False when comparing two stock exchange lists to return false, whereas common_tickers uses an intersection, which has to check both stock exchange lists.

**Comment by BasilBibi** [comment]
Good breakdown of justification - nice work.
