### ISSUE TITLE
Make sure concrete shopping cart Daos behave consistently when fetching by id finds nothing.

### ISSUE THREAD

**Issue by BasilBibi** [ZakBibi/PracticePython#98]

**Comment by BasilBibi** [comment]
Concrete shopping cart Daos should return None when fetching by id.

e.g. get_customer_by_id should return None if the given customer id is not found in the underlying data set.

**Comment by ZakBibi** [comment]
All shoppingcart Daos behave consistently when fetching by id finds nothing
